config-version: 1
properties:
  # Show debug messages.
  debug-messages: false

  # Help the developer know how popular the plugin is.
  use-metrics: true
  
  # How long to keep snapshots by default. Valid time suffixes: s|h|m|d|w.
  default-lifetime: 7d
  
  # How many results to show per page in the search command.
  rows-per-page: 8

  # Add white spaces to make columns line up. 
  add-whitespace-to-search: true

# Snapshot 
periodic-snapshots:
  # If enabled, give your players the 'ps.snapshot.periodic' permission.
  enabled: true
  # How long to keep the snapshot.
  lifetime: 3d
  # When to create snapshots. 
  interval: 1h

event-snapshots:
  #If enabled, give your players the 'ps.snapshot.player-death' permission.
  player-death: false

  # If enabled, give your players the 'ps.snapshot.player-login' permission.
  player-login: true

  # If enabled, give your players the 'ps.snapshot.world-enter' permission.
  world-enter: true
  
  # If enabled, give your players the 'ps.snapshot.world-leave' permission.
  # Only affects teleporting to different world (/mv, /warp, /tp, ect). Using a vanilla nether/enderportal will not trigger this.
  world-leave: true
  
messages:
  NoPermission: "You do not have permission: %s"
  RestoreAfterLogoff: "&f%s &7will be restored to &f%s &7when they log off."
  SnapshotDeleted: "&f%s&7's snapshot &f%s &7has been deleted."
  AddIndex: "&7Add the &aindex &7number from the search command."
  UseSearch: "&7Use the search command first."
  CreatedSnapshot: "&7Created snapshot (&f%s&7) for &f%s&7."
  SnapshotFailed: "&7Snapshot failed?"
  InvalidIndex: "&7Invalid index: &7%s"
  SnapRenamed: "&f%s &7has been renamed to &f%s&7."