config-version: 1
properties:
  # Show debug messages.
  debug-messages: false

  # Help the developer know how popular the plugin is.
  use-metrics: true
  
  # How long to keep snapshots by default. Valid time suffixes: s|h|m|d|w.
  default-lifetime: 7d
  
# Snapshot 
periodic-snapshots:
  # If enabled, give your players the 'ps.periodic-snapshot' permission.
  enabled: true
  # How long to keep the snapshot.
  lifetime: 3d
  # When to create snapshots. 
  interval: 1h

event-snapshots:
  player-death: true
  #If enabled, give your players the 'ps.event-snapshot.player-death' permission.
  
messages:
  NoPermission: "You do not have permission: %s"
  RestoreAfterLogoff: "&f%s &7will be restored to &f%s &7when they log off."